services:
    api:
        build: .
        container_name: subscriptionservice
        depends_on:
            - mongo
        ports:
            - "5000:8080"
    db:
        image: "mongo"
        environment:
            MONGODB_CONNECTION: mongodb+srv://Jacopo:jacopo123

    mongo:
        image: mongo
        container_name: adidaschallengejacopo
        restart: always
volumes:
        - mongodata:/data/adidasemailservices

volumes:
        db-data: